#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

. "$DIR/../lib/host.bash"

HOST_INSTANCE_TYPE="${BUILDKITE_PLUGIN_WIN_DOCKER_HOST_AWS_INSTANCE_TYPE:-t2.medium}"

launch_ec2_host "${HOST_INSTANCE_TYPE}"

