#!/usr/bin/env bash

set -euo pipefail

# AMI for Windows Server 2016 Containers: https://aws.amazon.com/marketplace/pp/B06XX3NFQF
# TODO: Search for this automatically
AP_SOUTHEAST2_AMI='ami-a4f22dc6'

HOST_INSTANCE_TYPE="${BUILDKITE_PLUGIN_WIN_DOCKER_HOST_AWS_INSTANCE_TYPE:-t2.medium}"

function get_local_ipv4() {
  curl -s 'http://169.254.169.254/latest/meta-data/local-ipv4'
}

function get_region() {
  curl -s 'http://169.254.169.254/latest/dynamic/instance-identity/document' | awk -F\" '/region/ {print $4}'
}

function get_mac_address() {
  curl -s 'http://169.254.169.254/latest/meta-data/mac'
}

function get_current_subnet_id() {
  local macAddress=$(get_mac_address)
  curl -s "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${macAddress}/subnet-id"
}

function get_vpc_id() {
  local macAddress=$(get_mac_address)
  curl -s "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${macAddress}/vpc-id"
}

function get_instance_id() {
  curl -s 'http://169.254.169.254/latest/meta-data/instance-id'
}

function create_security_group() {
  local vpcId="$1"
  local currentIp="$2"
  local instanceId=$(get_instance_id)
  local region=$(get_region)
  local groupId=$(aws ec2 create-security-group \
    --group-name "wdbp-${instanceId}" \
    --description 'Created by Win Docker Buildkite Plugin' \
    --vpc-id "${vpcId}" \
    --region "${region}" \
    --output text \
    --query 'GroupId')

  # allow docker 2375 on TCP
  aws ec2 authorize-security-group-ingress \
    --group-id "${groupId}" \
    --protocol tcp \
    --region "${region}" \
    --port 2375 \
    --cidr "$currentIp/32" > /dev/null

  echo "${groupId}"
}

function get_windows_userdata() {
  # Allow connection to the daemon per https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon
cat <<EOF | base64
<powershell>
\$daemonConfig = @'
{
  "hosts": ["tcp://0.0.0.0:2375", "npipe://"]
}
'@
\$daemonConfig | Out-File 'C:\ProgramData\Docker\config\daemon.json'
& netsh advfirewall firewall add rule name="Docker" dir=in action=allow protocol=TCP localport=2375
Restart-Service docker
</powershell>
EOF
}

function launch_ec2_host() {
  local region=$(get_region)
  local subnetId=$(get_current_subnet_id)
  local vpcId=$(get_vpc_id)
  local localIpv4=$(get_local_ipv4)
  local newSecurityGroupId=$(create_security_group "${vpcId}" "${localIpv4}")
  local userdata=$(get_windows_userdata)
  echo "--- :ec2: Launching Windows EC2 Instance for Windows Docker Container Support (${vpcId}, ${subnetId})"
  aws ec2 run-instances \
    --image-id "${AP_SOUTHEAST2_AMI}" \
    --count 1 \
    --instance-type "${HOST_INSTANCE_TYPE}" \
    --security-group-ids "${newSecurityGroupId}" \
    --user-data "${userdata}" \
    --region "${region}" \
    --subnet-id "${subnetId}"
}
